language: cpp
compiler: gcc
os: linux
sudo: required
dist: trusty
install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libtool automake autotools-dev autoconf pkg-config libssl-dev libcrypto++-dev libevent-dev git libboost-all-dev 
  - sudo add-apt-repository -y ppa:bitcoin/bitcoin
  - sudo apt-get update -y && sudo apt-get install -y libdb4.8-dev libdb4.8++-dev libzmq3-dev
  - sudo apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libcrypto++-dev libqrencode-dev
script:
  - ./autogen.sh && ./configure --with-gui && make
deploy:
  provider: releases
  file: "credits-qt"
  on:
tags: true
